functionsDirectory = "/Users/br14r/Documents/GitHub/sugarcypher/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/Users/br14r/Documents/GitHub/sugarcypher/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build:web:netlify"
functions = "/Users/br14r/Documents/GitHub/sugarcypher/netlify/functions"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run start-web"
port = 8081.0
publish = "dist"
framework = "#custom"

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]
Role = ["admin"]

[redirects.headers]